### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by zeeshan595** [maierfelix/nvk-essentials#1]
Hey, I was adding typescript support to this but i changed a bit too much so i created a separate npm package. Not sure if you want to merge it in because it is completely different. 

Here is a link for the pacakge, you can look at the forked repository for changes.
https://www.npmjs.com/package/nvk-essentials-js

If you do want to merge it in, I can create a pull request and remove my npm package :)

**Comment by zeeshan595** [comment]
Just want to add now you can use the following to easily manage array buffers

```ts
import { Data } from "nvk-essentials-js"

const data = new Data.DataController({
  test: [23, 43, 435], //By default every number gets converted to Float32Array
  test2: new Data.DataModel([2, 2, 2], Data.TypeOfData.Uint8) //Can specify the type using data model
});

const myAwesomeArrayBuffer = data.getArrayBuffer();
data.setArrayBuffer(myAwesomeArrayBuffer);

data.setData({
  test: [23, 234, 34],
  test2: new Data.DataModel([2, 2, 2], Data.TypeOfData.Uint8)
});
const myData = data.getData();
```

It also supports nesting objects, which is VERY handy

Example:
```ts
const data = new Data.DataController({
  transform: {
    position: [23, 23, 23],
    rotation: {
      angles: [23, 23, 23]
    }
  }
});
```

**Comment by maierfelix** [comment]
I'd happily merge a PR adding types to this:)
